import type { Metadata } from "next";
import { InfoPageShell } from "@/components/info-page";
import { BreadcrumbSchema } from "@/components/structured-data";
import { createPageMetadata } from "@/lib/page-metadata";

export const metadata: Metadata = createPageMetadata("Privacy Policy | Bloomie", "Learn how Bloomie handles website enquiries, WhatsApp and email conversations, hosting logs, and Instagram media used on this site.", "/privacy-policy");

export default function PrivacyPolicyPage() {
  return <><BreadcrumbSchema title="Privacy Policy" path="/privacy-policy" /><InfoPageShell title="Privacy Policy"><header className="info-intro"><span className="eyebrow">Privacy</span><h1>Privacy Policy</h1><p>Last updated: September 16, 2026</p></header><div className="policy-content"><section><h2>What this policy covers</h2><p>This policy explains how information may be handled when you use the Bloomie website or contact Bloomie about handmade crochet gifts, custom requests, or an order.</p></section><section><h2>Information you choose to share</h2><p>This website does not include a contact form or checkout. When you follow a WhatsApp link or email link, you may choose to share information such as your name, contact details, product enquiry, customisation request, and existing-order details in that conversation.</p><p>Please do not send sensitive payment information through the support channels listed on this site.</p></section><section><h2>How enquiry information is used</h2><p>Information shared in an enquiry may be used to respond to you, discuss a product or custom request, confirm order-related details, and provide support for an existing order.</p></section><section><h2>Services involved</h2><p>WhatsApp and email conversations are handled through the services you choose to use, and their own privacy terms apply. The website is hosted through infrastructure that may process standard technical request and log information to operate and secure the service.</p><p>The Fresh from Instagram section retrieves public post information through Meta&apos;s Instagram services. Images, videos, and thumbnails in that section may load directly from Instagram or Meta servers. Bloomie does not expose its Instagram access credentials in the browser.</p></section><section><h2>Cookies and analytics</h2><p>The current website implementation does not include analytics or advertising scripts, and it does not present a cookie consent banner. Third-party services may use their own cookies or similar technologies after you follow an external link; their policies apply to those interactions.</p></section><section><h2>Your questions and requests</h2><p>For help with personal information you have shared with Bloomie, email <a className="text-link" href="mailto:bloomiechrochetstore@gmail.com">bloomiechrochetstore@gmail.com</a>. Include enough context for Bloomie to understand your request, but do not include sensitive payment information.</p></section><section><h2>Policy updates</h2><p>This policy may be updated when the website or Bloomie&apos;s operating practices change. The date above shows when it was last updated.</p></section></div></InfoPageShell></>;
}
