import type { Metadata } from "next";
import { InfoPageShell } from "@/components/info-page";
import { BreadcrumbSchema } from "@/components/structured-data";
import { createPageMetadata } from "@/lib/page-metadata";

export const metadata: Metadata = createPageMetadata("Support | Bloomie", "Get Bloomie support for handmade crochet gifts, custom crochet requests, existing orders, and delivery questions in India.", "/support");

export default function SupportPage() {
  return <><BreadcrumbSchema title="Support" path="/support" /><InfoPageShell title="Support"><header className="info-intro"><span className="eyebrow">Here to help</span><h1>Support for your handmade order</h1><p>Ask about a Bloomie creation, a custom crochet gift, an existing order, or delivery before you order. We will help you continue the conversation in the channel that suits you.</p></header><div className="info-grid"><section><h2>Before you message</h2><p>For a product question, include the product name or a link to the item you are viewing. For a custom request, share the idea, preferred colours or sizing, and any relevant occasion details.</p><p>For an existing order, include the product name and the details already shared with Bloomie. Please do not send sensitive payment information in your message.</p></section><section><h2>Custom colours and sizing</h2><p>Bloomie welcomes custom crochet gifts and can discuss custom colours or sizing where those options are available. Availability, final price, and delivery details are confirmed over WhatsApp before an order is placed.</p><p>For handmade crochet tops, share your preferred sizing and ask about the specific design before ordering.</p></section><section><h2>Delivery questions</h2><p>Bloomie&apos;s listed preparation estimate is separate from delivery time. Ask before ordering to confirm delivery availability, delivery charges, and the expected timing for your selected creation.</p></section><section className="info-contact"><h2>Contact Bloomie</h2><p>Choose WhatsApp for an order or delivery question, or email Bloomie for support with an existing conversation.</p><div className="support-actions"><a className="button whatsapp" href="https://wa.me/917439792042" target="_blank" rel="noopener noreferrer">Chat on WhatsApp</a><a className="button ghost" href="mailto:bloomiechrochetstore@gmail.com">Email Bloomie</a></div><p>For quick answers to common questions, visit the <a className="text-link" href="/faq">FAQ</a>.</p></section></div></InfoPageShell></>;
}
